<template>
      <!-- form container -->
      <div class="w-full border-dashed border-gray-300 rounded p-10 flex justify-center border-2">
            <!-- form content -->
            <div class="w-full justify-between grid grid-cols-3 gap-7">
                  <!-- form title input -->
                  <text-input ref="title" @input="setFormTitle" :details="{ type:'text', label:'Form Title', placeholder:'Enter form title...', isRequired: true }" v-model="form.title"/>

                  <!-- form access level select input -->
                  <select-input ref="accessLevel" v-model="form.role" :details="{ label: 'Form Access Level', isRequired: true, options: roles, placeholder: 'Select form access level' }"/>

                  <!-- form editable and deletable checkboxes -->
                  <div class="flex justify-between items-center mt-5">
                        <check-box class="mb-2" :details="{ label: 'Is editable' }" v-model="form.isEditable" />
                        <check-box class="mb-2" :details="{ label: 'Is deletable' }" v-model="form.isDeletable" />
                  </div>

                  <!-- form fields generated by FieldGenerator component -->
                  <field-generator @handleModalState="handleModalState" @input="handleValue($event, component.label)" v-for="(component, index) in form.fields" :details="component" :key="`component-${index}`"></field-generator>

                  <!-- form alert message -->
                  <alert class="alert" v-if="showAlert" :message="alert.message" :type="alert.type" />
            </div>

            <!-- modal component for adding form fields -->
            <Modal @close="handleModalState(false)" v-show="openFormModal"/>
      </div>
      <div class="flex w-full justify-center mt-3">
            <btn @click="handleModalState(true)" bgColor="blue" textColor="black" class="self-center font-bold" text="Add Field"/>
            <btn @click.prevent="validateForm" bgColor="green" textColor="black" class="self-center font-bold ml-3" text="Submit"/>
      </div>
</template>

<script lang="ts">

// Importing components and utilities
import { defineComponent } from 'vue';
import SelectInput from '@/components/shared/BaseSelect/Select.vue';
import TextInput from '@/components/shared/BaseFormElements/TextInput/TextInput.vue';
import Btn from '@/components/shared/BaseButton/Button.vue';
import Modal from './FormBuilderModal.vue';
import FieldGenerator from '../FieldGenerator/index.vue';
import Alert from '@/components/shared/BaseAlert/Alert.vue'
import CheckBox from '@/components/shared/BaseFormElements/CheckBoxInput/CheckBoxInput.vue'

import { generateUniqueId as uuid } from '@/utils';

export default defineComponent({
      components: { SelectInput, Btn, TextInput, Modal, FieldGenerator, Alert, CheckBox },
      data(){
            return {
                  // list of available user roles for form access level
                  roles : [
                        { name: 'Admin', value: 'admin' },
                        { name: 'Guest', value: 'guest' }
                  ],

                  // list of available form actions
                  actions: [
                        { name: 'Delete', action: 'delete' },
                        { name: 'Edit', action: 'edit' },
                        { name: 'New', action: 'new' }
                  ],
                  
                  // form data
                  form: {
                        title: '',
                        role: '',
                        isEditable: false,
                        isDeletable: false,
                        fields: [] as any
                  } as any,
                  // State data for modal and alert
                  openFormModal: false,
                  hasError: false,
                  showAlert: false,
                  alert : {
                        type: '',
                        message: ''
                  }
            }
      },
      methods: {
            // Method to handle form field value change
            handleValue(e: Event | any, prop: { [key: string]: string}){
                  let currentItem = this.form.fields.find((item : any) => item.label === prop);
                  currentItem['value'] = e.target.value
                  return
            },
            // Method to add a form field
            addField(args: any){
                  if(!args.editingMode){
                        // Push new item to array
                        console.log(args)
                        this.form.fields.push(args.field);
                  } else {
                        // Edit existing item
                        const id = args.field.id;
                        const index = this.form.fields.map(function(e) { return e.id; }).indexOf(id);
                        this.form.fields.splice(index, 1, args.field);
                  }
                  this.handleModalState(false)
            },
            // Method to handle alert message
            handleAlert( obj: { type: string, message: string } ){
                  const { type, message } = obj;
                  this.alert.type = type;
                  this.alert.message = message;
                  this.showAlert = true;
                  setTimeout(() => {
                        this.showAlert = false
                  }, 3000);
            },
            // Method to validate form fields   
            validateForm(e: Event){
                  e.preventDefault();
                  this.checkForErrors();
            },
            // Method to check for form field errors
            checkForErrors(){
                  const refs = this.$refs;
                  const errors : boolean[] = [];
                  Object.keys(refs).forEach( key => {
                        const ref = refs[key] as any;
                        if( !ref ) return;
                        ref.setValidators();
                        errors.push(ref.hasError)
                  })
                  this.hasError = errors.some(i => i);
                  !this.hasError && this.submitForm()
            },
            getExistingForms(): []{
                  // Retrieve the form data from local storage
                  return JSON.parse(localStorage.getItem('form')!) || [];
            },
            // Method to submit the form
            submitForm(){
                  if(this.form.fields.length < 1){
                        this.handleAlert({ type: 'error', message: 'Form must have 1 field at least.'})
                        return
                  }
                  // Define the array of forms
                  const forms: any[] = this.getExistingForms();

                  // Existance of id means the mode is edit
                  const id : string = localStorage.getItem('currentFormId')!;
                  if(id){
                        let currentForm = forms.find((i : any) => i.id === id);
                        Object.assign(currentForm, this.form);
                  } else {
                        forms.push({...this.form, id: uuid()});
                  }
                  
                  localStorage.removeItem('form');
                  localStorage.removeItem('currentFormId');
                  // Save the updated array to local storage
                  localStorage.setItem('form', JSON.stringify(forms));

                  //Change component to list of forms;
                  this.emitter.emit('setCurrentItem', 'Forms')
                  this.handleAlert({ type: 'success', message: 'Form submitted successfully.'})
            },
            setFormTitle(){
                  // Set title for form and add to Main component ot show in UI.
                  this.emitter.emit('setFormName', this.form.title &&`${this.form.title} Form`)
            },
            handleModalState(state: boolean, action?: string, details?: any){
                  /**
                        This function updates the state of the 'openFormModal' variable based on the 'state' parameter value.
                        If 'action' parameter has the value 'edit', it emits an event 'setAvailableFormDetails' using the 'details' parameter as data.
                        If 'action' parameter has the value 'delete', it removes an object from the 'fields' array property of the 'form' object,
                        using the 'details.id' property value to identify the object to be removed.
                        @param {boolean} state - A boolean value indicating the new state for 'openFormModal' variable.
                        @param {string | undefined} action - A string parameter that determines the action to be taken.
                        @param {any | undefined} details - An optional parameter that contains additional details required for the 'action' parameter.
                        @returns {void}
                  */
                  this.openFormModal = state;
                  if(action === 'edit'){
                        this.emitter.emit('setAvailableFormDetails', details);
                  } else if(action === 'delete') {
                        const id = details?.id;
                        const index = this.form.fields.map(function(e : any) { return e.id }).indexOf(id);
                        this.form.fields.splice(index, 1);
                  }
            },
            checkLocalStorage(){
                  localStorage.getItem('currentFormId') && this.setCurrentFormDetails();
            },
            setCurrentFormDetails(){
                  // It retrieves the ID of the current form from the 'currentFormId' key in local storage and
                  // retrieves the list of forms from the 'form' key in local storage, which is parsed from JSON to an object.
                  const id : string = localStorage.getItem('currentFormId')!;
                  const forms : any = JSON.parse(localStorage.getItem('form')!);
                  const currentForm = forms.find((item: any) => item.id === id);
                  this.form = {...currentForm};
            }
      },
      mounted(){
            this.checkLocalStorage();
            this.emitter.on('addFormFields', this.addField);
      }

})
</script>

<style>
.alert {
      position: absolute;
      top: 5%;
      left: 50%;
}
</style>